main:
  referece / actual zmp:
    legends:
      - { key: reference cog, id: [0-2] }
      - { key: actual cog, id: [0-2] }
      - { key: reference zmp, id: [0-2] }
      - { key: modified reference zmp, id: [0-2] }
      - { key: actual zmp, id: [0-2] }

  act/ref cog velocity:
    legends:
      - { key: st_originActCogVel, id: [0-2]}
      - { key: st_originRefCogVel, id: [0-2]}

  act/ref force:
    legends:
      - { key: rmfo_off_rfsensor, id: [2] }
      - { key: rmfo_off_lfsensor, id: [2] }
      - { key: st_ref_rfsensor, id: [2] }
      - { key: st_ref_lfsensor, id: [2] }

  # act/ref moment:
  #   legends:
  #     - { key: rmfo_off_rfsensor, id: [3-5] }
  #     - { key: rmfo_off_lfsensor, id: [3-5] }
  #     - { key: st_ref_rfsensor, id: [3-5] }
  #     - { key: st_ref_lfsensor, id: [3-5] }

  # optional_data:
  #   legends:
  #     - { key: abc_contactStates, id: [0-3] }
  #     - { key: abc_controlSwingSupportTime, id: [0-3] }

