main:
  # referece / actual zmp:
  #   legends:
  #     - { key: reference cog, id: [0-2], label: ref com }
  #     - { key: actual cog, id: [0-2], label: act com }
  #     - { key: reference zmp, id: [0-2], label: ref zmp }
  #     - { key: modified reference zmp, id: [0-2], label: new zmp }
  #     - { key: actual zmp, id: [0-2], label: act zmp }
  Reference / actual COM and ZMP on the X axis:
    legends:
      - { key: reference cog, id: [0], label: ref com }
      - { key: actual cog, id: [0], label: act com }
      - { key: reference zmp, id: [0], label: ref zmp }
      - { key: modified reference zmp, id: [0], label: new zmp }
      - { key: actual zmp, id: [0], label: act zmp }
    left_label: "X [m]"
    newline: false

  Reference / actual COM and ZMP on the Y axis:
    legends:
      - { key: reference cog, id: [1], label: ref com }
      - { key: actual cog, id: [1], label: act com }
      - { key: reference zmp, id: [1], label: ref zmp }
      - { key: modified reference zmp, id: [1], label: new zmp }
      - { key: actual zmp, id: [1], label: act zmp }
    left_label: "Y [m]"
    newline: false

  Reference / actual COM on the Z axis:
    legends:
      - { key: reference cog, id: [2], label: ref com }
      - { key: actual cog, id: [2], label: act com }
    left_label: "Z [m]"

  Refernce / actual COM velocity on the X axis:
    legends:
      - { key: st_originRefCogVel, id: [0], label: ref com vel}
      - { key: st_originActCogVel, id: [0], label: act com vel}

  act/ref force:
    legends:
      - { key: rmfo_off_rfsensor, id: [2] }
      - { key: rmfo_off_lfsensor, id: [2] }
      - { key: st_ref_rfsensor, id: [2] }
      - { key: st_ref_lfsensor, id: [2] }

  # act/ref moment:
  #   legends:
  #     - { key: rmfo_off_rfsensor, id: [3-5] }
  #     - { key: rmfo_off_lfsensor, id: [3-5] }
  #     - { key: st_ref_rfsensor, id: [3-5] }
  #     - { key: st_ref_lfsensor, id: [3-5] }

  # optional_data:
  #   legends:
  #     - { key: abc_contactStates, id: [0-3] }
  #     - { key: abc_controlSwingSupportTime, id: [0-3] }

